function output=get_lickrate_byTrialType(trialData,trials,trialType,edges)
% % get_lickrate_byTrialType %
%PURPOSE:   Analyze lick rate for different trial types
%AUTHORS:   AC Kwan 170518
%
%INPUT ARGUMENTS
%   trialData:  Structure generated by MP_getSessionData().
%   trials:     Structure generated by MP_getTrialMasks().
%   trialType:  The trial types (fieldnames of the trials variable)
%   edges:      The edges used for a histc() operation to get lick rate histogram
%
% To plot the output, use plot_lickrate_byTrialType().

%% 

leftTimes=[]; 
rightTimes=[]; 
edgeWidth=nanmean(diff(edges));

for i=1:numel(trialType)
    
    %trials belonging to specific outcome or rule type
    tempMask = trials.(trialType{i});
    
    %histogram of all left lick times = left lick rate
    temp=histc([trialData.leftlickTimes{tempMask}],edges)/sum(tempMask)/edgeWidth;   %in Hz
    if ~isempty(temp)    %if there are any such trials and licks
        leftTimes{i}=temp(1:end-1)';
    else                 %otherwise fill with NaN
        leftTimes{i}=nan(size(edges(1:end-1)'));
    end
    
    %histogram of all right lick times = right lick rate    
    temp=histc([trialData.rightlickTimes{tempMask}],edges)/sum(tempMask)/edgeWidth;   %in Hz
    if ~isempty(temp)    
        rightTimes{i}=temp(1:end-1)';
    else
        rightTimes{i}=nan(size(edges(1:end-1)'));
    end
    
end

output.trialType=trialType;
output.edges=edges;
output.leftTimes=leftTimes;
output.rightTimes=rightTimes;

end


