function plot_session_beh_vert(trialData,trials,blocks,tlabel,time_range)
% % plot_session_beh_vert %
%PURPOSE:   Plot bandit task performance, vertical view
%AUTHORS:   AC Kwan 170518
%
%INPUT ARGUMENTS
%   trialData:    Structure generated by MP_getSessionData().
%   trials:       Structure generated by MP_getTrialMasks().
%   blocks:       Structure generated by value_getBlockData().
%   tlabel:       Text to put as title of the plot
%   time_range:   Time in seconds to plot, e.g., [-2 6], around the cue

batchSize=100; %plot in batches of 100 trials

nTrials=numel(trials.left);
numBatch=ceil(nTrials/batchSize);

for l=1:numBatch
    figure; hold on;
    title({tlabel;'{\color{green}Reward} {\color{magenta}No reward} {\color{black}L Licks} {\color{red}R Licks}'});
    trial1=(l-1)*batchSize+1;
    trial2=trial1+batchSize-1;
    if trial2>nTrials
        trial2=nTrials;
    end
    
    for j=trial1:trial2
        refTime=trialData.cueTimes(j);
        
        %draw the outcome
        if trials.reward(j)
            color='g';
        elseif trials.noreward(j)
            color='m';
        else
            color='w';        
        end
        eventTime=trialData.outcomeTimes(j);
        eventDur=3;
        p=fill([eventTime-refTime eventTime+eventDur-refTime eventTime+eventDur-refTime eventTime-refTime],[j-0.5 j-0.5 j+0.5 j+0.5],color);
        set(p,'Edgecolor',color);
        
        %draw licks
        ll=trialData.leftlickTimes{j};
        plot([ll; ll],j+[-0.5*ones(size(ll)); 0.5*ones(size(ll))],'k','LineWidth',2);
        rl=trialData.rightlickTimes{j};
        plot([rl; rl],j+[-0.5*ones(size(rl)); 0.5*ones(size(rl))],'r','LineWidth',2);
        
    end
    if ~isempty(blocks)
        for j=1:length(blocks.firstTrial)
            plot([time_range(1) time_range(2)],(blocks.firstTrial(j)-0.5)*[1 1],'k');
        end
    end
    xlim([time_range(1),time_range(2)]);
    ylim([trial1-1 trial1+100]);
    set(gca, 'ydir','reverse')
    xlabel('Time (s)');
    ylabel('Trial');
    
    print(gcf,'-dpng',['session_vert-' int2str(l)]);    %png format
    %saveas(gcf, ['session_vert-' int2str(l)], 'fig');
    
end

end


