% convert .csv files generated by deeplabcut to pupildiameter data
filepath = 'E:\labcode\pupil\868_1DeepCut_resnet50_PupillometryMay31shuffle1_200000.csv';
% matpath = 'E:\data\pupildata\huriye\M18102_phase8_R71NoCue_WithPupil_1901141057.mat';


% load(matpath);
% sumFrames = 0;
% allRadius = [];
%for ii = 1:length(pupData)
%    sumFrames = sumFrames + length(pupData(ii).radius);
%    allRadius = [allRadius, pupData(ii).radius'];
%end

% skip first 4 rows 
M = csvread(filepath,3);
upX = M(:, 2); upY = M(:,3);
downX = M(:,5); downY = M(:,6);
leftX = M(:,8); leftY = M(:,9);
rightX = M(:,11); rightY = M(:,12);
centerX = M(:,14); centerY = M(:,15);

diaVer = sqrt((upX-downX).^2+(upY-downY).^2);
diaHor = sqrt((leftX-rightX).^2+(leftY-rightY).^2);

figure;
plot(diaVer, 'LineWidth',2);
hold on;
plot(diaHor, 'LineWidth',2);

radius = (diaVer+diaHor)/4;

figure; 
xAxis = 1:length(diaVer);
sz = 100;
scatter(xAxis, diaVer, sz, '.');
% figure;
% plot(radius, 'LineWidth',2);
% hold on;
% plot(allRadius,'LineWidth',2);


% check 