function [stackInfo, pupilDia] = loadPupilFiles(pupilCSV, pupilMat)

% load pupil .csv and .mat files 
% input: pupilCSV: csv file generated by deeplabcut
%        pupilMat: mat file generated by matlab while recording (frame per
%        trial)
% output: stackInfo: frame per trial
%         pupilDia: pupil horizontal diameter (px) calculated from csv file
%         pupilCenter: pupil center position (px) calculated from csv file
%         (use the very first center position as the origin, identifying saccade?) 
           

% load pupil .mat file
stackInfo = load(fullfile(pupilMat.folder,pupilMat.name));

% load pupil .csv file
pupilDia = loadPupil(fullfile(pupilCSV.folder,pupilCSV.name));


end