function MP_plot_extreme(input,tlabel,xtitle)
% % MP_plot_psth %
%PURPOSE:   Plot extremeties to show whether it influences the bootstrap
%           estimation
%AUTHORS:   hongli
%
%INPUT ARGUMENTS
%   input:        Structure generated by MP_get_psth().
%   tlabel:       Text to put as title of the plot.
%   xtitle:       Text to put as the label for x-axis.

%% Plotting parameters
colors={'k','r','b','g'};
gray=[0.7 0.7 0.7];

%% Setup
t=input(1).sig{1}.t;
nPanel=numel(input);  %how many panel?

nSig=[];    %how many signals/psth in each panel?
for j=1:nPanel
    nSig(j)=numel(input(j).sig);
end

%set up the y-axis range 
if isfield(input(1).sig{1},'bootlow') %if CIs are available, use those to set the range
    templow=[]; temphigh=[];
    for j=1:nPanel
        for k=1:nSig(j)
            templow=[templow; input(j).sig{k}.bootlow];
            temphigh=[temphigh; input(j).sig{k}.boothigh];
        end
    end
    minY=nanmin(templow)-0.5;
    maxY=nanmax(temphigh)+0.5;
else
    tempsig=[];
    for j=1:nPanel
        for k=1:nSig(j)
            tempsig=[tempsig; input(j).sig{k}.signal];
        end
    end
    minY=nanmin(tempsig)-0.2;
    maxY=nanmax(tempsig)+0.2;
end

%% 
figure;
for j=1:nPanel
    
    subplot(1,nPanel,j); hold on;
    
    % plot the extremeties
    
    for k=1:nSig(j)
        maxValue = max(input(j).sig{k}.bootSig,[],2);
        minValue = min(input(j).sig{k}.bootSig,[],2);
        
        % get the difference
        maxDiff = maxValue - input(j).sig{k}.bootavg;
        minDiff = minValue - input(j).sig{k}.bootavg;
        
        deviateIndMax = maxDiff > 0.1;
        deviateIndMin = minDiff < -0.1;
        figure;
        plot(maxDiff);
        hold on; plot(minDiff);
        
        % plot a histogram
        x = 1:110;
        xMax = x(deviateIndMax);
        tt = input(j).sig{k}.bootSig(:,xMax(25));
        figure;
        histogram(tt);
        figure;histogram(input(j).sig{k}.bootSig(:,1));
    end
    
    % plot the shaded errors
    if isfield(input(j).sig{k},'bootlow') %if CIs are available, plot them
        for k=1:nSig(j)
            errorshade(t,input(j).sig{k}.bootlow,input(j).sig{k}.boothigh,gray);
        end
    end
    
    % plot the mean signals again so they lie on top of shaded errors
    for k=1:nSig(j)
        plot(t,input(j).sig{k}.signal,colors{k});
    end
    
    plot([0 0],[minY maxY],'k','LineWidth',2);
    xlabel(xtitle); ylabel('dF/F');
    ylim([minY maxY]);
    xlim([t(1) t(end)]);
    title(tlabel);
    
end

end


