function MP_plot_pupil( pupil, trialData)
% % plot_allCells %
%PURPOSE:   Plot pupil in one imaging session
%AUTHORS:   Hongli
%
%INPUT ARGUMENTS
%   pupil:        Structure generated by start_pupil_compute
%   trialData:    Structure generated by MP_getSessionData().

%% Display parameters

spacing = 2;     % in unit of dF/F
faceAlpha = 0.2; % transparency for rule type colors

nCells = 1;
t = (pupil.t / 60); %Unit: seconds->minutes
startTimes = (trialData.cueTimes ./ 60); %Unit: seconds->minutes

%%

    %Make color-coded backdrop for each rule block
figure; hold on;

x1 = startTimes(1); %Time of first trial in ith block
x2 = t(end);


% fill([x1;x1;x2;x2],[y1;y2-spacing;y2-spacing;y1],'FaceAlpha',faceAlpha,'EdgeColor','none'); hold on;

    
%Plot dF/F for all cells


plot(t,pupil.dia - spacing,'LineWidth',1);
ylabel('z-score'); xlabel('Time (min)');
xlim([t(1) t(end)]);
    
print(gcf,'-dpng',['pupil' ]);    %png format
saveas(gcf, ['pupil' ], 'fig');
    
end
