function MP_plot_regr_iti(iti1,iti2,iti3,pvalThresh,tlabel,xtitle)
% % MP_plot_regr_PN %
%PURPOSE:   Plot results from choice term separated by positive/negative
%coefficient
%AUTHORS:   AC Kwan 170515
%
%INPUT ARGUMENTS
%   input:        Structure generated by linear_regr().
%   pvalThresh:   Threshold value to deem whether p-values are significant
%   tlabel:       Text to put as title of the plot.
%   xtitle:       Text to put as the label for x-axis.

%% setup
t=iti1.regr_time;
dt=nanmean(diff(t));

nCells=size(iti1.coeff,3);
for j=1:nCells
    pval1(:,:,j)=iti1.pval(:,:,j);
    pval2(:,:,j)=iti2.pval(:,:,j);
    pval3(:,:,j)=iti3.pval(:,:,j);
end

nPredictor=3; % reward n, n-1, n-2
panelv = 3;

nback=0;



%% plot results

figure;

for l=1:1
          
   %subplot(1,3,l); hold on;

   %patch([t(1) t(end) t(end) t(1)],[0 0 100*pvalThresh 100*pvalThresh],[0.7 0.7 0.7],'EdgeColor','none');
   if strcmp(tlabel{1}, 'C(n+1)')
       l = 1;
   elseif strcmp(tlabel{1},'C(n)')
       l = 2;
   elseif strcmp(tlabel{1},'C(n-1)')
       l = 3;
   elseif strcmp(tlabel{1},'R(n+1)')
       l = 5;
   elseif strcmp(tlabel{1}, 'R(n-1)')
       l = 7;
   end
   plot(t,100*sum((pval1(:,l+1,:)<pvalThresh),3)/nCells,'.-','MarkerSize',30);hold on;
   plot(t,100*sum((pval2(:,l+1,:)<pvalThresh),3)/nCells,'.-','MarkerSize',30);hold on;
   plot(t,100*sum((pval3(:,l+1,:)<pvalThresh),3)/nCells,'.-','MarkerSize',30);

   legend('Short < 5.26','Median','Long > 6.50');
   legend boxoff
   plot([0 0],[0 100],'k','LineWidth',1);
   xlim([t(1) t(end)]);
   ylim([0 40]);
   title(tlabel{1});
   xlabel(xtitle);
   ylabel('Fraction of sessions (%)');
   
   set(gca,'box','off');
%         identifying significant points via binomial test
%         sig=[];
%         for ll=1:numel(t)
%             [p]=myBinomTest(sum(pval(ll,currPredictor,:)<pvalThresh,3),nCells,pvalThresh);
%             sig(ll)=p;
%         end
%         for ll=1:numel(sig)
%             if sig(ll)<pvalThresh
%                 plot(t(ll)+dt*[-0.5 0.5],[75 75],'k-','LineWidth',5);
%             end
%         end
%     end
end


end
