function MP_plot_regr_PN(input,pvalThresh,tlabel,xtitle)
% % MP_plot_regr_PN %
%PURPOSE:   Plot results from choice term separated by positive/negative
%coefficient
%AUTHORS:   AC Kwan 170515
%
%INPUT ARGUMENTS
%   input:        Structure generated by linear_regr().
%   pvalThresh:   Threshold value to deem whether p-values are significant
%   tlabel:       Text to put as title of the plot.
%   xtitle:       Text to put as the label for x-axis.

%% setup
t=input.regr_time;
dt=nanmean(diff(t));

nCells=size(input.coeff,3);
for j=1:nCells
    pval(:,:,j)=input.pval(:,:,j);
end

nPredictor=1; % current choice
panelv = 3;

nback=0;



%% plot results

figure;

for l=1:3
          
   subplot(2,2,l); hold on;

   patch([t(1) t(end) t(end) t(1)],[0 0 100*pvalThresh 100*pvalThresh],[0.7 0.7 0.7],'EdgeColor','none');
   if l==1 % plot positive
        plot(t,100*sum((pval(:,2,:)<pvalThresh&input.coeff(:,2,:)>0),3)/nCells,'k.-','MarkerSize',30);
   elseif l==2 % plot negative
       plot(t,100*sum((pval(:,2,:)<pvalThresh&input.coeff(:,2,:)<0),3)/nCells,'k.-','MarkerSize',30);
   else  % plot pos-neg
       plot(t,100*abs(sum((pval(:,2,:)<pvalThresh&input.coeff(:,2,:)>0),3)-sum((pval(:,2,:)<pvalThresh&input.coeff(:,2,:)<0),3))/nCells,'k.-','MarkerSize',30);
   end 
       plot([0 0],[0 100],'k','LineWidth',1);
        xlim([t(1) t(end)]);
        ylim([0 100]);
        title(tlabel{l});
        xlabel(xtitle);
        ylabel('Fraction of sessions (%)');
        
%         identifying significant points via binomial test
%         sig=[];
%         for ll=1:numel(t)
%             [p]=myBinomTest(sum(pval(ll,currPredictor,:)<pvalThresh,3),nCells,pvalThresh);
%             sig(ll)=p;
%         end
%         for ll=1:numel(sig)
%             if sig(ll)<pvalThresh
%                 plot(t(ll)+dt*[-0.5 0.5],[75 75],'k-','LineWidth',5);
%             end
%         end
%     end
end


end
