function MP_plot_regrRL_pupil(input,pvalThresh,tlabel,xtitle)
% % plot_regr %
%PURPOSE:   Plot results from multiple linear regression
%AUTHORS:   AC Kwan 170515
%
%INPUT ARGUMENTS
%   input:        Structure generated by linear_regr().
%   pvalThresh:   Threshold value to deem whether p-values are significant
%   tlabel:       Text to put as title of the plot.
%   xtitle:       Text to put as the label for x-axis.

%% setup
t{1}=input(1).regr_time;
dt{1}=nanmean(diff(t{1}));

% t{2}=input(2).regr_time;
% dt{2}=nanmean(diff(t{2}));

nCells=numel(input);
for j=1:nCells
    pval{j}=input(j).pval;
    coeff{j} = input(j).coeff;
end

nPredictor=input.numPredictor;

% nback=input.nback;

%% plot results

figure;

for jj = 1:nCells
    for l=1:nPredictor
        currPredictor=l+nPredictor * (jj-1) + 1; %first +1 because first term is bias
        
        if nPredictor ==7
            subplot(2, 4, l); hold on;
        elseif nPredictor == 6
            subplot(2,3,l); hold on;
        elseif nPredictor == 12
            subplot(3,4,l); hold on;
        % patch([t(1) t(end) t(end) t(1)],[0 0 100*pvalThresh 100*pvalThresh],[0.7 0.7 0.7],'EdgeColor','none');
        plot(t{jj},coeff{jj}(:,currPredictor),'k.-','MarkerSize',30);
        
        xlim([t{jj}(1) t{jj}(end)]);
        title(tlabel{l});
        xlabel(xtitle{jj});
        ylabel('Coefficients');
        yl = ylim;
        % get significant point
        for ii = 1:length(pval{jj}(:,l))
            if pval{jj}(ii,l) < pvalThresh
                hold on;
                scatter(t{jj}(ii),1.5,25,'filled','black');
            end
        end
        ylim([-1 1.5]);
        plot([0 0],[-1 1.5],'k','LineWidth',1);
        
    end
end

end
