function MP_plot_regr_two(input1,input2, input_ctrl, pvalThresh,tlabel,xtitle,control)
% % plot_regr %
%PURPOSE:   Plot results from multiple linear regression
%AUTHORS:   AC Kwan 170515
%
%INPUT ARGUMENTS
%   input:        Structure generated by linear_regr().
%   input_ctrl:   control values of significant sessions, if [] indicate no
%                   contrl, then use binomial test
%   pvalThresh:   Threshold value to deem whether p-values are significant
%   tlabel:       Text to put as title of the plot.
%   xtitle:       Text to put as the label for x-axis.

%% setup

% check whether a control regression exist
if ~exist('control','var')
    % third parameter does not exist, so default it to something
    exist_control = 0;
else
    exist_control = 1;
end

t=input1.regr_time;
dt=nanmean(diff(t));

nCells=size(input1.pval,3);

    pval1(:,:,:)=input1.pval;
    pval2(:,:,:)=input2.pval;


nPredictor=input1.numPredictor;

nback=input1.nback;

if (input1.interaction == true)
    if nPredictor == 2
        panelv = nPredictor + 1;    %plot extra row for the interaction terms
        nInteraction = 1;
    else
        panelv = nPredictor + 2;    %plot extra row for the interaction terms
        nInteraction = 2;
    end
else
    panelv = nPredictor;
    nInteraction = 0;
end

%% plot results

figure;

for l=1:nPredictor
    for k=1:1+nback
        currPredictor=1+k+(l-1)*(1+nback); %first +1 because first term is bias
        
        if nPredictor == 7  % C(n+1) regression
            subplot(2,4,currPredictor-1); hold on;
             [if_xlabel,if_ylabel] = if_label(currPredictor, nPredictor, nback);
        elseif nPredictor == 5
            subplot(2,3,currPredictor-1); hold on;
             [if_xlabel,if_ylabel] = if_label(currPredictor, nPredictor, nback);
        elseif nPredictor == 2 & nback == 0  % Pos/neg RPE
            subplot(1,2,currPredictor-1); hold on;
             [if_xlabel,if_ylabel] = if_label(currPredictor, nPredictor, nback);
        elseif nPredictor == 14 % for future choice and reward
            subplot(4,4, currPredictor-1); hold on;
             [if_xlabel,if_ylabel] = if_label(currPredictor, nPredictor, nback);
        elseif nPredictor == 10  % for dQ and chosenQ plot
            subplot(4,3,currPredictor-1); hold on;
             [if_xlabel,if_ylabel] = if_label(currPredictor, nPredictor, nback);
        elseif nPredictor == 6  % for RPE/updatedQ
            subplot(2,3,currPredictor-1); hold on;
        elseif nPredictor == 12  % for RL with choice autocorrelation
            subplot(4,3,currPredictor-1); hold on;
             [if_xlabel,if_ylabel] = if_label(currPredictor, nPredictor, nback);
        elseif nPredictor == 9  % for RL with choice autocorrelation
            subplot(3,3,currPredictor-1); hold on;
            [if_xlabel,if_ylabel] = if_label(currPredictor, nPredictor, nback);
        else
            subplot(panelv,1+nback,currPredictor-1); hold on;
            [if_xlabel,if_ylabel] = if_label(currPredictor, nPredictor, nback)
        end
        %patch([t(1) t(end) t(end) t(1)],[0 0 100*pvalThresh 100*pvalThresh],[0.7 0.7 0.7],'EdgeColor','none');
        percentage1 = 100*sum(pval1(:,currPredictor,:)<pvalThresh,3)/nCells;
        percentage2 = 100*sum(pval2(:,currPredictor,:)<pvalThresh,3)/nCells;
        
        % chi-square test to determine if they are signficantly different
       n1 = sum(pval1(:,currPredictor,:)<pvalThresh,3); N1 = nCells;
       n2 = sum(pval2(:,currPredictor,:)<pvalThresh,3); N2 = nCells;
       % Pooled estimate of proportion
       p0 = (n1+n2) ./ (N1+N2);
       % Expected counts under H0 (null hypothesis)
       n10 = N1 * p0;
       n20 = N2 * p0;
       % Chi-square test, by hand
       observed = [n1'; N1'-n1'; n2'; N2'-n2'];
       expected = [n10'; N1'-n10'; n20'; N2'-n20'];
       chi2stat = sum((observed-expected).^2 ./ expected);
       p = 1 - chi2cdf(chi2stat,1);
        %plot(t,percentage,'k.-','MarkerSize',15);
        %if isempty(input_ctrl)
        plot(t,percentage1,'-','color',[0.4940 0.1840 0.5560]);
        hold on; plot(t,percentage2,'-','color',[0.9290 0.6940 0.1250]);
%         else
%             fieldName = ['trigEvent',num2str(currPredictor-1)];
%             for ll=1:numel(percentage)
%                 if input_ctrl.(fieldName).boothigh(ll) < percentage(ll)
%                     if ll==1
%                         plot(t(ll)+dt*[-0.5 0.5],[(percentage(ll)+percentage(ll))/2 (percentage(ll)+percentage(ll+1))/2],'-','Color',[0 0 0],'LineWidth',5);
%                     elseif ll==length(percentage)
%                         plot(t(ll)+dt*[-0.5 0.5],[(percentage(ll)+percentage(ll))/2 (percentage(ll)+percentage(ll))/2],'g-','LineWidth',5);
%                     else
%                         plot(t(ll)+dt*[-0.5 0],[(percentage(ll)+percentage(ll-1))/2 percentage(ll)],'-','Color',[0 0 0],'LineWidth',7);
%                         plot(t(ll)+dt*[0 0.5], [percentage(ll) (percentage(ll)+percentage(ll+1))/2],'-','Color',[0 0 0],'LineWidth',7);
%                     end
%                 else % not significant
%                     if ll==1
%                         plot(t(ll)+dt*[-0.5 0.5],[(percentage(ll)+percentage(ll))/2 (percentage(ll)+percentage(ll+1))/2],'k-','LineWidth',5);
%                     elseif ll==length(percentage)
%                         plot(t(ll)+dt*[-0.5 0.5],[(percentage(ll)+percentage(ll))/2 (percentage(ll)+percentage(ll))/2],'k-','LineWidth',5);
%                     else
%                         plot(t(ll)+dt*[-0.5 0],[(percentage(ll)+percentage(ll-1))/2 percentage(ll)],'k-','LineWidth',7);
%                         plot(t(ll)+dt*[0 0.5], [percentage(ll) (percentage(ll)+percentage(ll+1))/2],'k-','LineWidth',7);
%                     end
%                     
%                 end
%             end
%         end
        plot([0 0],[0 100],'k','LineWidth',1);
        xlim([floor(t(1)) ceil(t(end))]);
        xticks([floor(t(1)):1:ceil(t(end))]);
        ylim([0 104]);
        title(tlabel{currPredictor-1});
        if if_xlabel ~= 1
            set(gca,'xticklabel',[])
        end
        if if_xlabel == 1
            xlabel(xtitle);
        end
        if if_ylabel == 1
            ylabel_txt = {'Fraction of','sessions (%)'};
            ylabel(ylabel_txt);
        end

        %identifying significant points via binomial test
       

            %ifSig = sig<pvalThresh/10;
            %start1 = strfind([0, ifSig],[0,1]);
            %end1 = strfind([ifSig, 0],[1,0]);

            for ll=1:numel(p)
                if p(ll)<0.05
                    plot(t(ll)+dt*[-0.5 0.5], [104 104],'k-','LineWidth',5);
                end
                %plot(t(ll)+dt*[-0.5 0.5], [95 95],'-','Color',[1 sig(ll) sig(ll)],'LineWidth',5);
            end
% 
%         else
%             % control regression exist
%             fieldName = ['trigEvent',num2str(currPredictor-1)];
%             
%             % find the continuous significant part
% %             ifSig = (input_ctrl.(fieldName).boothigh < percentage);
% %             start1 = strfind([0, ifSig'],[0,1]);
% %             end1 = strfind([ifSig', 0],[1,0]);
% % 
% %             for ll = 1:length(start1)
% %                 plot(t(start1(ll):end1(ll)), percentage(start1(ll):end1(ll)),'-','Color',[1 0.5 0],'LineWidth',5);
% %             end
%             sig = input_ctrl.(fieldName).pval;
%             sig(sig<=1e-3) = 1e-3;
%             %sig(sig>=0.05) = 1;
%             logSig = log(sig)/log(1e-3);
%             for ll=1:numel(sig)
%                 plot(t(ll)+dt*[-0.5 0.5], [95 95],'-','Color',[1 1-logSig(ll) 1-logSig(ll)],'LineWidth',5);
%                 %plot(t(ll)+dt*[-0.5 0.5], [95 95],'-','Color',[1 sig(ll) sig(ll)],'LineWidth',5);
%             end
% 
%         end
    end
    


    %% for 4*3 (row*col)
    if nPredictor == 10 || nPredictor == 12
        pos = get(gca, 'Position');
        pos(4) = 0.13;
        pos(3) = 0.23;
        set(gca, 'Position', pos)
    elseif nPredictor == 14
    % for 4*4
        pos = get(gca, 'Position');
        pos(4) = 0.13;
        pos(3) = 0.15;
        set(gca, 'Position', pos)
    %% for 3*3
    elseif nPredictor == 9
        pos = get(gca, 'Position');
        pos(4) = 0.21;
        pos(3) = 0.23;
        set(gca, 'Position', pos)
    end
end
end

