function plot_logreg_opto(input,tlabel)    
% % plot_logreg_opto %
%PURPOSE:   Plot logistic regression analysis of choice behavior
%           (session in which subset of trials were perturbed)
%AUTHORS:   AC Kwan 170518
%
%INPUT ARGUMENTS
%   input:  Structure generated by logistic_reg_opto().
%   tlabel: Text string that will be put on top of the figure

%%
if numel(input)>1  %more than 1 data set, plot mean+-sem
    n=input{1}.n;
    b_label=input{1}.b_label;

    for j=1:numel(input)
        temp_bias(j)=input{j}.b_bias_ctrl;
        temp_coeff(:,:,j)=input{j}.b_coeff_ctrl;
        temp_bias_opto(j)=input{j}.b_bias_opto;
        temp_coeff_opto(:,:,j)=input{j}.b_coeff_opto;
    end
    b_bias=nanmean(temp_bias);
    b_coeff=nanmean(temp_coeff,3);
    b_bias_opto=nanmean(temp_bias_opto);
    b_coeff_opto=nanmean(temp_coeff_opto,3);
    b_bias_sem=nanstd(temp_bias)./sqrt(numel(input));
    b_coeff_sem=nanstd(temp_coeff,[],3)./sqrt(numel(input));
    b_bias_opto_sem=nanstd(temp_bias_opto)./sqrt(numel(input));
    b_coeff_opto_sem=nanstd(temp_coeff_opto,[],3)./sqrt(numel(input));
else        %plot the 1 data set
    n=input.n;
    b_bias=input.b_bias_ctrl;
    b_coeff=input.b_coeff_ctrl;
    b_bias_opto=input.b_bias_opto;
    b_coeff_opto=input.b_coeff_opto;
    b_label=input.b_label;
end

numcoeffType = size(b_coeff,2); %number of types of coefficients
colors = cbrewer('qual', 'Set1', numcoeffType);

trialIntoPast = -1*n;

figure; hold on;
for j=1:numcoeffType
    plot(trialIntoPast,b_coeff(:,j),'.-','MarkerSize',30,'LineWidth',3,'Color',colors(j,:));
end
for j=1:numcoeffType
    plot(trialIntoPast,b_coeff_opto(:,j),'.--','MarkerSize',30,'LineWidth',3,'Color',colors(j,:));
end
plot([-100 100],[0 0],'k--','LineWidth',2);
plot(0,b_bias,'k.','MarkerSize',30);
plot(0,b_bias_opto,'b.','MarkerSize',30);
if numel(input)>1
    for j=1:numcoeffType
        for k=1:numel(trialIntoPast)
            plot(trialIntoPast(k)*[1 1],b_coeff(k,j)+b_coeff_sem(k,j)*[-1 1],'-','LineWidth',3,'Color',colors(j,:));
            plot(trialIntoPast(k)*[1 1],b_coeff_opto(k,j)+b_coeff_opto_sem(k,j)*[-1 1],'-','LineWidth',3,'Color',colors(j,:));
        end
    end
    plot([0 0],b_bias+b_bias_sem*[-1 1],'k-','LineWidth',3);
    plot([0 0],b_bias_opto+b_bias_opto_sem*[-1 1],'b-','LineWidth',3);
end
xlim([-0.5 trialIntoPast(end)+0.5]);
legend(b_label,'Location','Northeast');
xlabel('Trials into past')
ylabel('Outcome history weight')
title(tlabel);

end
