function plot_logreg(input,tlabel)
% % plot_logreg %
%PURPOSE:   Plot logistic regression analysis of choice behavior
%AUTHORS:   AC Kwan 170518
%
%INPUT ARGUMENTS
%   input:  Structure generated by logistic_reg().
%   tlabel: Text string that will be put on top of the figure

%%
pvalThresh = 0.001;      %criterion for stat. significance for the coefficients
fracsig_Thresh = 0.5;   %if >50% of the animals/sessions have stat. sig coefficient, then denote it with a triangle in the plot

if numel(input)>1  %more than 1 data set, plot mean+-sem
    n=input{1}.n;
    b_label=input{1}.b_label;
    
    for j=1:numel(input)
        temp_bias(j)=input{j}.b_bias;
        temp_coeff(:,:,j)=input{j}.b_coeff;

        temp_pval_bias(j)=input{j}.pval_bias;
        temp_pval_coeff(:,:,j)=input{j}.pval_coeff;    
    end
    b_bias=nanmean(temp_bias);
    b_coeff=nanmean(temp_coeff,3);
    b_bias_sem=nanstd(temp_bias)./sqrt(numel(input));
    b_coeff_sem=nanstd(temp_coeff,[],3)./sqrt(numel(input));
    
    maxY=max([b_bias+b_bias_sem max(b_coeff(:)+b_coeff_sem(:))]);
    
    %fraction of session/animal inputs have regression coefficients that
    %are statistically significant
    fracsig_bias=sum(temp_pval_bias<pvalThresh)/numel(input);
    for k=1:size(temp_pval_coeff,1)
        for l=1:size(temp_pval_coeff,2)
            fracsig_coeff(k,l)=sum(temp_pval_coeff(k,l,:)<pvalThresh)/numel(input);
        end
    end
else        %plot the 1 data set
    n=input.n;
    b_bias=input.b_bias;
    b_coeff=input.b_coeff;
    b_label=input.b_label;
    
    maxY=max([b_bias max(b_coeff)]);
    
    fracsig_bias=(input.pval_bias<pvalThresh);
    fracsig_coeff=(input.pval_coeff<pvalThresh);
end

numcoeffType = size(b_coeff,2); %number of types of coefficients
colors = cbrewer('qual', 'Set1', numcoeffType);

trialIntoPast = -1*n;

figure; 
subplot(2,2,1); hold on;
for j=1:numcoeffType
    plot(trialIntoPast,b_coeff(:,j),'.-','MarkerSize',30,'LineWidth',3,'Color',colors(j,:));
end
plot([-100 100],[0 0],'k--','LineWidth',2);
plot(0,b_bias,'k.','MarkerSize',30);

%plot error bars
if numel(input)>1
    for k=1:numel(trialIntoPast)
        for j=1:numcoeffType
            plot(trialIntoPast(k)*[1 1],b_coeff(k,j)+b_coeff_sem(k,j)*[-1 1],'-','LineWidth',3,'Color',colors(j,:));
        end
    end
    plot([0 0],b_bias+b_bias_sem*[-1 1],'k-','LineWidth',3);
end

%plot larger markers for stat. significant data points
for k=1:numel(trialIntoPast)
    for j=1:numcoeffType
        if fracsig_coeff(k,j)>=fracsig_Thresh
            plot(trialIntoPast(k),maxY*(1.6-0.2*j),'v','MarkerSize',15,'LineWidth',3,'MarkerEdgeColor',colors(j,:));
        end
    end
end
if fracsig_bias>=fracsig_Thresh
    plot(0,maxY*1.4,'v','MarkerSize',15,'LineWidth',3,'MarkerFaceColor','w','MarkerEdgeColor','k');
end

xlim([-0.5 trialIntoPast(end)+0.5]);
set(gca,'XDir','reverse')
ylim([-1*1.5*maxY 1.5*maxY]);
legend(b_label,'Location','Southeast');
xlabel('Trials into past')
ylabel('Outcome history weight')
title(tlabel);

end
