function plot_switch(input,tlabel,rule_labels)
% % plot_switch %
%PURPOSE:   Plot choice behavior around switches of all possible types
%AUTHORS:   AC Kwan 170518
%
%INPUT ARGUMENTS
%   input:  Structure generated by choice_switch().
%   tlabel: Text string that will be put on top of the figure
%   rule_labels:    Text strings for the legend in figure

%%
if numel(input)>1  %more than 1 data set, plot mean+-sem
    n=input{1}.n;
    numtransType=input{1}.numtransType;
    transType=input{1}.transType;
    for j=1:numel(input)
        temp_probl(:,:,j)=input{j}.probl;
        temp_probr(:,:,j)=input{j}.probr;
    end
    probl=nanmean(temp_probl,3);
    probr=nanmean(temp_probr,3);
    probl_sem=nanstd(temp_probl,[],3)./sqrt(numel(input));
    probr_sem=nanstd(temp_probr,[],3)./sqrt(numel(input));
else        %plot the 1 data set
    n=input.n;
    probl=input.probl;
    probr=input.probr;
    numtransType=input.numtransType;
    transType=input.transType;
end

colors = cbrewer('qual', 'Set1', numtransType);

figure;
subplot(1,2,1); hold on;
legstring=[];
for j=1:numtransType
    plot(n,probl(:,j),'.-','MarkerSize',30,'Linewidth',3,'Color',colors(j,:));
    legstring{j}=[rule_labels{transType(j,1)} '->' rule_labels{transType(j,2)}];
end
plot([0 0],[0 1],'k--','LineWidth',2);
if numel(input)>1
    for j=1:numtransType
        for l=1:numel(n)
            plot(n(l)*[1 1],probl(l,j)+probl_sem(l,j)*[-1 1],'-','LineWidth',3,'Color',colors(j,:));
        end
    end
end
legend(legstring);
ylabel('P_{Left}');
xlabel('Trials from block switch');
axis([n(1) n(end) 0 1]);
title(tlabel);

subplot(1,2,2); hold on;
for j=1:numtransType
    plot(n,probr(:,j),'.-','MarkerSize',30,'Linewidth',3,'Color',colors(j,:));
end
plot([0 0],[0 1],'k--','LineWidth',2);
if numel(input)>1
    for j=1:numtransType
        for l=1:numel(n)
            plot(n(l)*[1 1],probr(l,j)+probr_sem(l,j)*[-1 1],'-','LineWidth',3,'Color',colors(j,:));
        end
    end
end
legend(legstring);
ylabel('P_{Right}');
xlabel('Trials from block switch');
axis([n(1) n(end) 0 1]);

print(gcf,'-dpng','switches');    %png format
saveas(gcf, 'switches', 'fig');

end


    