function output=get_val_byTrialType(val,trials,trialType,edges,valLabel)
% % get_val_byTrialType %
%PURPOSE:   Analyze value (e.g., response time) for different trial types
%AUTHORS:   AC Kwan 170518
%
%INPUT ARGUMENTS
%   val:        Vector for the values
%   trials:     Structure generated by value_getTrialMasks().
%   trialType:  The trial types (fieldnames of the trials variable)
%   edges:      The edges used for a histc() operation to get lick rate histogram
%   valLabel:   Text to describe what the value is, and will put as label for x-axis.
%
% To plot the output, use plot_lickrate_byTrialType().

%% 

edgeWidth=nanmean(diff(edges));

for i=1:numel(trialType)
    
    %trials belonging to specific outcome or rule type
    tempMask = (trials.(trialType{i})==1);
    tempMask(isnan(tempMask))=0;
    
    %histogram
    temp=histc(val(tempMask>0),edges);   
    if ~isempty(temp)    %if there are any such trials and licks
        val_byTrType{i}=temp(1:end-1);
    else                 %otherwise fill with NaN
        val_byTrType{i}=nan(size(edges(1:end-1)'));
    end
    
    %median
    valMedian{i} = nanmedian(val(tempMask));
end

output.trialType=trialType;
output.edges=edges;
output.val=val_byTrType;
output.valMedian=valMedian;
output.valLabel=valLabel;

end


