function plot_switch_hrside_random(input,tlabel)
% % plot_switch_hrside_random %
%PURPOSE:   Plot choice behavior around switches, when the high reward
%           side has changed
%AUTHORS:   AC Kwan 170518
%
%INPUT ARGUMENTS
%   input:  Structure generated by choice_switch_hrside().
%   tlabel: Text string that will be put on top of the figure

%%
if numel(input)>1  %more than 1 data set, plot mean+-sem
    n=input{1}.n;
    numRange=input{1}.numRange;
    L1_ranges=input{1}.L1_ranges;
    L2_ranges=input{1}.L2_ranges;
    for j=1:numel(input)
        temp_probh(:,:,j)=input{j}.probh;
        temp_probl(:,:,j)=input{j}.probl;
        temp_probn(:,:,j)=input{j}.probneither;
    end
    probh=nanmean(temp_probh,3);
    probl=nanmean(temp_probl,3);
    probn=nanmean(temp_probn,3);
    probh_sem=nanstd(temp_probh,[],3)./sqrt(numel(input));
    probl_sem=nanstd(temp_probl,[],3)./sqrt(numel(input));
    probn_sem=nanstd(temp_probn,[],3)./sqrt(numel(input));
else        %plot the 1 data set
    n=input.n;
    probh=input.probh;
    probl=input.probl;
    probn=input.probneither;
    numRange=input.numRange;
    L1_ranges=input.L1_ranges;
    L2_ranges=input.L2_ranges;
end

figure;
subplot(1,2,1); hold on;

legendNum = 1;

%plot dotted line at trial = 0
plot([0 0],[0 1],'k--','LineWidth',2);

%plot probability of choosing initial best option
for k=1:numRange
    %plot the mean
    h(legendNum) = plot(n,probh(:,k),'.-','MarkerSize',30,'Linewidth',3,'Color',[0 1 k/(numRange+1)]);
    %if more than 1 data set, then plot the error bars
    if numel(input)>1
        for l=1:numel(n)
            plot(n(l)*[1 1],probh(l,k)+probh_sem(l,k)*[-1 1],'-','LineWidth',3,'Color',[0 1 k/(numRange+1)]);
        end
    end
    
    legstring{legendNum}=['Initial better option (L_1: ' int2str(L1_ranges(k,1)) '-' int2str(L1_ranges(k,2)) '; L_2: ' int2str(L2_ranges(k,1)) '-' int2str(L2_ranges(k,2)) ')'];
    legendNum = legendNum + 1;
end

%plot probability of choosing initial worse option
for k=1:numRange
    %plot the mean
    h(legendNum) = plot(n,probl(:,k),'.-','MarkerSize',30,'Linewidth',3,'Color',[1 k/(numRange+1) 1]);
    %if more than 1 data set, then plot the error bars
    if numel(input)>1
        for l=1:numel(n)
            plot(n(l)*[1 1],probl(l,k)+probl_sem(l,k)*[-1 1],'-','LineWidth',3,'Color',[1 k/(numRange+1) 1]);
        end
    end
    
    legstring{legendNum}=['Initial worse option (L_1: ' int2str(L1_ranges(k,1)) '-' int2str(L1_ranges(k,2)) '; L_2: ' int2str(L2_ranges(k,1)) '-' int2str(L2_ranges(k,2)) ')'];
    legendNum = legendNum + 1;
end

%plot probability of choosing neither
for k=1:numRange
    %plot the mean
    h(legendNum) = plot(n,probn(:,k),'.-','MarkerSize',30,'Linewidth',3,'Color',k/(numRange+1)*[1 1 1]);
    %if more than 1 data set, then plot the error bars
    if numel(input)>1
        for l=1:numel(n)
            plot(n(l)*[1 1],probn(l,k)+probn_sem(l,k)*[-1 1],'-','LineWidth',3,'Color',k/(numRange+1)*[1 1 1]);
        end
    end
    
    legstring{legendNum}=['Miss (L_1: ' int2str(L1_ranges(k,1)) '-' int2str(L1_ranges(k,2)) '; L_2: ' int2str(L2_ranges(k,1)) '-' int2str(L2_ranges(k,2)) ')'];
    legendNum = legendNum + 1;
end

legend(h,legstring);
legend box off;
ylabel('Fraction of trials');
xlabel('Trial from block switch');
axis([n(1) n(end) 0 1]);
title(tlabel);

end


