function plot_switch_hrside(input,tlabel)
% % plot_switch_hrside %
%PURPOSE:   Plot choice behavior around switches, when the high reward
%           side has changed
%AUTHORS:   AC Kwan 170518
%
%INPUT ARGUMENTS
%   input:  Structure generated by choice_switch_hrside().
%   tlabel: Text string that will be put on top of the figure

%%
if numel(input)>1  %more than 1 data set, plot mean+-sem
    n=input{1}.n;
    for j=1:numel(input)
        temp_probh(:,j)=input{j}.probh;
        temp_probl(:,j)=input{j}.probl;
        temp_probn(:,j)=input{j}.probneither;
    end
    probh=nanmean(temp_probh,2);
    probl=nanmean(temp_probl,2);
    probn=nanmean(temp_probn,2);
    probh_sem=nanstd(temp_probh,[],2)./sqrt(numel(input));
    probl_sem=nanstd(temp_probl,[],2)./sqrt(numel(input));
    probn_sem=nanstd(temp_probn,[],2)./sqrt(numel(input));
else        %plot the 1 data set
    n=input.n;
    probh=input.probh;
    probl=input.probl;
    probn=input.probneither;
end

figure;
subplot(1,2,1); hold on;
plot(n,probh,'.-','MarkerSize',30,'Linewidth',3,'Color','g');
plot(n,probl,'.-','MarkerSize',30,'Linewidth',3,'Color','m');
plot(n,probn,'.-','MarkerSize',30,'Linewidth',3,'Color','k');
plot([0 0],[0 1],'k--','LineWidth',2);
if numel(input)>1
    for l=1:numel(n)
        plot(n(l)*[1 1],probh(l)+probh_sem(l)*[-1 1],'-','LineWidth',3,'Color','g');
        plot(n(l)*[1 1],probl(l)+probl_sem(l)*[-1 1],'-','LineWidth',3,'Color','m');
        plot(n(l)*[1 1],probn(l)+probn_sem(l)*[-1 1],'-','LineWidth',3,'Color','k');
    end
end
ylabel('Fraction of trials');
xlabel('Trial from block switch');
legend('Initial better option','Initial worse option','Miss');
legend box off;
axis([n(1) n(end) 0 1]);
title(tlabel,'interpreter','none');

end


    