function plot_logreg(input,tlabel)
% % plot_logreg %
%PURPOSE:   Plot logistic regression analysis of choice behavior
%AUTHORS:   AC Kwan 170518
%
%INPUT ARGUMENTS
%   input:  Structure generated by logistic_reg().
%   tlabel: Text string that will be put on top of the figure

%%
pvalThresh = 0.01;      %criterion for stat. significance

if numel(input)>1  %more than 1 data set, plot mean+-sem
    n=input{1}.n;
    b_label=input{1}.b_label;
    
    for j=1:numel(input)
        temp_bias(j)=input{j}.b_bias;
        temp_coeff(:,:,j)=input{j}.b_coeff;
    end
    
    % calculating median!
    % if using mean - plot could be skewed by a few sessions/animals with very
    % large coefficients due to ill-conditioned regression analysis
    b_bias=nanmedian(temp_bias);
    b_coeff=nanmedian(temp_coeff,3);
    
    %statistical significance - non-parametric sign-rank test against zero
    pval_bias = signrank(temp_bias);
    for k=1:size(temp_coeff,1)
        for j=1:size(temp_coeff,2)
            pval_coeff(k,j) = signrank(squeeze(temp_coeff(k,j,:)));
        end
    end

else        %plot the 1 data set
    n=input.n;
    b_bias=input.b_bias;
    b_coeff=input.b_coeff;
    b_label=input.b_label;
end

maxY=max([b_bias max(b_coeff(:))]);

numcoeffType = size(b_coeff,2); %number of types of coefficients
colors(1,:) = [0 0 0];  %black
colors(2,:) = [1 0 1];  %magenta
colors(3,:) = [0 1 1];  %cyan
colors(4,:) = [0 1 0];  %green

trialIntoPast = -1*n;

figure; 
subplot(2,2,1); hold on;
for j=1:numcoeffType
    plot(trialIntoPast,b_coeff(:,j),'.-','MarkerSize',30,'LineWidth',3,'Color',colors(j,:));
end
plot([-100 100],[0 0],'k--','LineWidth',2);
plot(0,b_bias,'k.','MarkerSize',30);

%plot markers for stat. significant data points
if numel(input)>1  %more than 1 data set, can calculate significance    
    for k=1:numel(trialIntoPast)
        for j=1:numcoeffType
            if pval_coeff(k,j)<pvalThresh
                plot(trialIntoPast(k),maxY+0.3*(numcoeffType-j+1),'v','MarkerSize',15,'LineWidth',3,'MarkerEdgeColor',colors(j,:));
            end
        end
    end
    if pval_bias<pvalThresh
        plot(0,maxY+0.3,'v','MarkerSize',15,'LineWidth',3,'MarkerFaceColor','w','MarkerEdgeColor','k');
    end
end

xlim([-0.5 trialIntoPast(end)+0.5]);
set(gca,'XDir','reverse');
ylim([-0.7 maxY+0.3*numcoeffType+0.1]);
legend(b_label,'Location','Southeast');
legend box off;
xlabel('Trial into past')
ylabel('Weight')
title(tlabel,'interpreter','none');

end
