function plot_val_byTrialType(input)
% % plot_val_byTrialType %
%PURPOSE:   Plot lick rates for different trial types
%AUTHORS:   AC Kwan 170518
%
%INPUT ARGUMENTS
%   input:        Structure generated by get_lickrate_byTrialType().

%%
% if called from single-session analysis, input is a struct
% if called from summary analysis, input is a cell array
% here convert everything to a cell array first
if ~iscell(input)
    temp = input;
    clear input;
    input{1} = temp;
end

% load from the cell array
edges=input{1}.edges;
trialType=input{1}.trialType;

val = [];
for j=1:numel(trialType)
    for l=1:numel(input)
        val(j,:,l)=input{l}.val{j};
    end
end

%% calculate sum, mean, and sem

for j=1:numel(trialType)
    val_mean(:,j)=nanmean(val(j,:,:),3);    
end

%% plot

figure;

minY=nanmin(val_mean(:));
maxY=nanmax(val_mean(:));
panel_h=numel(trialType);

edges=edges+nanmean(diff(edges))/2; %plot at the center of the bins

for j=1:numel(trialType)
    
    subplot(2,panel_h,j); hold on;
    bar(edges(1:end-1),val_mean(:,j),'FaceColor','k');    
    plot([0 0],[minY maxY],'k--','LineWidth',2);
    xlim([edges(1) edges(end)]);
    ylim([minY maxY]);
    title(trialType{j},'interpreter','none');
    ylabel('Number of trials');
    xlabel(input{1}.valLabel);
    
end

end


