function plot_switch(input,tlabel,rule_labels)
% % plot_switch %
%PURPOSE:   Plot choice behavior around switches
%AUTHORS:   AC Kwan 170518
%
%INPUT ARGUMENTS
%   input:  Structure generated by choice_switch().
%   tlabel: Text string that will be put on top of the figure
%   rule_labels:    Text strings for the legend in figure

%%
if numel(input)>1  %more than 1 data set, plot mean+-sem
    n=input{1}.n;
    numtransType=input{1}.numtransType;
    transType=input{1}.transType;
    for j=1:numel(input)
        temp_probl(:,:,j)=input{j}.probl;
        temp_probr(:,:,j)=input{j}.probr;
        temp_probn(:,:,j)=input{j}.probneither;
    end
    probl=nanmean(temp_probl,3);
    probr=nanmean(temp_probr,3);
    probn=nanmean(temp_probn,3);
    probl_sem=nanstd(temp_probl,[],3)./sqrt(numel(input));
    probr_sem=nanstd(temp_probr,[],3)./sqrt(numel(input));
    probn_sem=nanstd(temp_probn,[],3)./sqrt(numel(input));
else                %plot the 1 data set
    n=input.n;
    probl=input.probl;
    probr=input.probr;
    probn=input.probneither;
    numtransType=input.numtransType;
    transType=input.transType;
end

figure;

for j=1:numtransType
    
    subplot(1,numtransType,j); hold on;
    %plot the mean
    plot(n,probl(:,j),'.-','MarkerSize',30,'Linewidth',3,'Color','r');
    plot(n,probr(:,j),'.-','MarkerSize',30,'Linewidth',3,'Color','b');
    plot(n,probn(:,j),'.-','MarkerSize',30,'Linewidth',3,'Color','k');
    %plot dotted line at trial = 0
    plot([0 0],[0 1],'k--','LineWidth',2);
    %if more than 1 data set, then plot the error bars
    if numel(input)>1
        for l=1:numel(n)
            plot(n(l)*[1 1],probl(l,j)+probl_sem(l,j)*[-1 1],'-','LineWidth',3,'Color','r');
            plot(n(l)*[1 1],probr(l,j)+probr_sem(l,j)*[-1 1],'-','LineWidth',3,'Color','b');
            plot(n(l)*[1 1],probn(l,j)+probn_sem(l,j)*[-1 1],'-','LineWidth',3,'Color','k');
        end
    end
    
    legend({'Left','Right','Miss'});
    legend box off;
    ylabel('Fraction of trials');
    xlabel('Trial from block switch');
    axis([n(1) n(end) 0 1]);
    title([rule_labels{transType(j,1)} ' to ' rule_labels{transType(j,2)}]);
    
end

end


